name: halkculator
description: "Profit calculator app"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Localization
  easy_localization: ^3.0.3

  # Animation
  lottie: ^3.1.0

  # State management
  provider: ^6.1.1

  # Database
  hive_flutter: ^1.1.0
  uuid: ^4.3.3

  # Ad
  google_mobile_ads: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  flutter_native_splash: ^2.3.6

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/halkculator.png
  color_dark: "#000000"
  android_12:
    image: assets/images/halkculator.png
    color: "#ffffff"
    color_dark: "#000000"
    fullscreen: true
  android: true
  ios: true
  fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/
    - assets/animation/
